export enum FileMediaErrorCode {
  INVALID_APP_ID = 'INVALID_APP_ID',
  INVALID_FILE_ID = 'INVALID_FILE_ID',
  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_ALREADY_DELETED = 'FILE_ALREADY_DELETED',
  FILE_NOT_RECOVERABLE = 'FILE_NOT_RECOVERABLE',
  FILE_MUST_BE_DELETED = 'FILE_MUST_BE_DELETED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  BULK_LIMIT_EXCEEDED = 'BULK_LIMIT_EXCEEDED',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  STORAGE_OPERATION_FAILED = 'STORAGE_OPERATION_FAILED',
  PERSISTENCE_OPERATION_FAILED = 'PERSISTENCE_OPERATION_FAILED',
  ADMIN_KEY_REQUIRED = 'ADMIN_KEY_REQUIRED',
  ADMIN_KEY_INVALID = 'ADMIN_KEY_INVALID',
}

export class FileMediaError extends Error {
  constructor(
    readonly code: FileMediaErrorCode,
    message: string,
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = FileMediaError.name;
  }
}
